name: Publish React app on push

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Checkout publish branch
        uses: actions/checkout@v2
        with:
          ref: publish 

      - name: Copy build files to publish branch
        run: |
          cp -r build/* .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update build files"
          git push
